---
- name: get repos 1/2
  get_url:
    url: http://repository.egi.eu/community/software/preview.repository/2.0/releases/repofiles/centos-7-x86_64.repo 
    dest: /etc/yum.repos.d/centos-7-x86_64.repo

- name: get repos 2/2
  get_url:
    url: http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo 
    dest: /etc/yum.repos.d/EGI-trustanchors.repo

- name: install 1/2 
  yum:
    name: 
      - epel-release 
      - yum-plugin-ovl
    state: latest

- name: install 2/2
  yum:
    name: 
      - fetch-crl 
      - wn 
      - sysstat
      - ca-policy-egi-core 
      - ca-policy-lcg
      - xrootd-server
    state: latest

- name: fetch-crl -q
  command: /usr/sbin/fetch-crl -q

- name: enable service fetch-crl-cron and ensure it is not masked
  systemd:
    name: fetch-crl-cron
    enabled: yes
    masked: no

- name: Make sure fetch-crl-cron is running
  systemd: state=started name=fetch-crl-cron 

- name: get metricbeat rpm
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.2.4-x86_64.rpm
    dest: /tmp/metricbeat-6.2.4-x86_64.rpm

- name: install metricbeat
  yum:
    name: /tmp/metricbeat-6.2.4-x86_64.rpm
    state: latest
