- name: wait 10 minutes for nodes to be configured
  wait_for: timeout=600
  delegate_to: localhost
- name: "Compile config template XCache"
  template:
    src: templates/k8s/k8s_template.yml
    dest: /etc/XCache_deployment.yml
- name: "Deploy XCache on Kubernetes"
  command: kubectl create -f /etc/XCache_deployment.yml
